version: "3.8"

services:

  # Relational Data Base if project goes to production
  db:
    restart: always
    image: postgres:13-alpine
    container_name: demo-postgres #you can change this
    environment: 
        - POSTGRES_DB=app
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  
  # UI to interact with posgres sql data base
  pgadmin:
      image: dpage/pgadmin4
      container_name: demo-pgadmin #you can change this
      depends_on:
        - db
      ports:
        - "5051:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: root
      restart: always


volumes:
  .:
  postgres_data: